version: '3.6'
services:
  freeipa:
    image: docker.service:5000/daex-meta/freeipa
    deploy:
      placement:
        constraints:
          - node.labels.freeipa == true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0        
    hostname: ipa.daex.lan
    volumes:
      - type: volume
        source: ipa-data
        target: /data
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        read_only: true
      - type: tmpfs
        target: /run
      - type: tmpfs
        target: /tmp
    ports:
      - 8080:80
      - 4431:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp  
    networks:
      docproc2:
        aliases:
          - ipa.daex.lan      
volumes:
  ipa-data:      
networks:
  docproc2:
    external: true
