version: '3'
services:
  nginx:
    image: docker.service:5000/daex-meta/nginx
    deploy:
      placement:
        constraints:
          - node.labels.nginx == true      
    hostname: nginx
    volumes:
      - conf:/etc/nginx
      - html:/usr/share/nginx/html
    networks:
      - docproc2        
    ports:
      - 4431:443
      - 8080:80  
volumes:
  conf:
  html:        
networks:
  docproc2:
    external: true
